// src/app.svelte
<script>
  import { onMount } from "svelte";
  import BootupScreen from '🍎/components/Desktop/BootupScreen.svelte';
  import Route from "🍎/components/pager/route.svelte";
  import Router from "🍎/components/pager/router.svelte";
  import DesktopPage from "🍎/pages/home-page.svelte";
  import NotFoundPage from "🍎/pages/not-found-page.svelte";
  import { useAuth0 } from '🍎/services/auth0';

  let authParams;

  let { isLoading, isAuthenticated, login, initializeAuth0, error } = useAuth0;

  const authenticationGuard = (ctx, next) => {
    if ($isAuthenticated) {
      next();
    } else {
      login({ appState: { targetUrl: ctx.pathname } });
    }
  };

  const onRedirectCallback = (appState) => {
    console.log('app.onRedirectCallback')
    console.log(`app.onRedirectCallback targetURL`, appState.targetUrl)
    console.log(`app.onRedirectCallback pathName:`, window.location.pathname)

    window.history.replaceState(
      {},
      document.title,
      appState && appState.targetUrl
        ? appState.targetUrl
        : window.location.pathname
    );
  };

  onMount(async () => {
    await initializeAuth0({ onRedirectCallback });

    console.log('app.onMount')
    const params = new URLSearchParams(window.location.search);
    for (const [key, value] of params.entries()) {
      console.log(`app.onMount param: key=> ${key} value=>${value}`)
    }
    
    console.log(`app.onMount AUTHENTICATED`, isAuthenticated)
  });
</script>

{#if $isLoading}
  <div class="page-layout">
  </div>
{:else}
  <Router>
    <Route path="/" component={DesktopPage} middleware={[authenticationGuard]}/>
    <Route path="*" component={NotFoundPage} />
  </Router>
{/if}

// src/App.tsx
import React from 'react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import { Auth0Provider, useAuth0 } from './contexts/Auth0Context';
import DesktopPage from './pages/HomePage';
import NotFoundPage from './pages/NotFoundPage';
import LoginScreen from './components/Auth/LoginScreen';
import LoadingScreen from './components/Auth/LoadingScreen';
import ErrorBoundary from './components/ErrorBoundary';

const AuthenticatedApp: React.FC = () => {
  const { isLoading, isAuthenticated, error, user } = useAuth0();

  console.log('Auth state:', { isLoading, isAuthenticated, error, user });

  if (isLoading) {
    console.log('Showing loading screen');
    return <LoadingScreen />;
  }

  // Only show login screen for errors if user is not authenticated
  if (error && !isAuthenticated) {
    console.error('Auth error:', error);
    return <LoginScreen />;
  }

  if (!isAuthenticated) {
    console.log('Not authenticated, showing login');
    return <LoginScreen />;
  }

  console.log('Authenticated, showing desktop');
  return (
    <Routes>
      <Route path="/" element={<DesktopPage />} />
      <Route path="*" element={<NotFoundPage />} />
    </Routes>
  );
};

const App: React.FC = () => {
  return (
    <ErrorBoundary>
      <Auth0Provider>
        <BrowserRouter>
          <AuthenticatedApp />
        </BrowserRouter>
      </Auth0Provider>
    </ErrorBoundary>
  );
};

export default App;
